<?php
/**
* Vincent Enjalbert
*
* Version Française :
* *****************************************************************************
*
* Notification de la Licence
*
* Ce fichier source est sujet au CLUF
* qui est fourni avec ce module dans le fichier LICENSE-FR.txt.
* Il est également disponible sur le web à l'adresse suivante:
* http://www.web-cooking.net/licences/magento/LICENSE-FR.txt
*
* =============================================================================
*        NOTIFICATION SUR L'UTILISATION DE L'EDITION MAGENTO
* =============================================================================
* Ce module est conçu pour l'édition COMMUNITY de Magento
* WebCooking ne garantit pas le fonctionnement correct de cette extension
* sur une autre édition de Magento excepté l'édition COMMUNITY de Magento.
* WebCooking ne fournit pas de support d'extension en cas
* d'utilisation incorrecte de l'édition.
* =============================================================================
*
* English Version :
* *****************************************************************************
*
* NOTICE OF LICENSE
*
* This source file is subject to the EULA
* that is bundled with this package in the file LICENSE-EN.txt.
* It is also available through the world-wide-web at this URL:
* http://www.web-cooking.net/licences/magento/LICENSE-EN.txt
*
* =============================================================================
*                 MAGENTO EDITION USAGE NOTICE
* =============================================================================
* This package designed for Magento COMMUNITY edition
* WebCooking does not guarantee correct work of this extension
* on any other Magento edition except Magento COMMUNITY edition.
* WebCooking does not provide extension support in case of
* incorrect edition usage.
* =============================================================================
*
* @category   Webcooking
* @package    Webcooking_Productredirection
* @copyright  Copyright (c) 2011-2013 Vincent René Lucien Enjalbert
* @license    http://www.web-cooking.net/licences/magento/LICENSE-EN.txt
 */
?>
<script type="text/javascript">
    var helper = 'Url helper : ';
    //helper += '<a href="<?php echo $this->getProductGridUrl() ?>">TestProduct</a>  ';
    helper += '<a href="javascript:void(0);" onclick="javascript:loadProductGrid();">Product</a>  ';
    helper += '<a href="javascript:void(0);" onclick="javascript:loadCategoryGrid();">Category</a>  ';
    helper += '<a href="javascript:void(0);" onclick="javascript:loadPageGrid();">Page</a>  ';
    helper += '<a href="javascript:void(0);" onclick="javascript:setProductRedirectionUrl(\'<?php echo $this->getHomepageUrl() ?>\')">Home Page</a>  ';
    $('product_redirection_url').insert({after:helper})
    $('product_redirection_url').up().up().insert({after:'<tr><td colspan="3"><div id="product-redirection-helper"></div></td></tr>'});
    
    function setProductRedirectionUrl(url) {
        $('product-redirection-helper').innerHTML = '';
        $('product_redirection_url').value = url;
    }
    
    function loadPrGrid(url) {
        new Ajax.Updater(
            'product-redirection-helper',
            url,
            {
                    method: 'get',
                    evalScripts:true,
                    insertion: Insertion.Bottom
            }
        );
    }
    
    function loadProductGrid() {
       $('product-redirection-helper').innerHTML = '';
       loadPrGrid('<?php echo $this->getProductGridUrl() ?>');
    }
    
    function loadCategoryGrid() {
       $('product-redirection-helper').innerHTML = '';
       loadPrGrid('<?php echo $this->getCategoryGridUrl() ?>');
    }
    
    function loadPageGrid() {
       $('product-redirection-helper').innerHTML = '';
       loadPrGrid('<?php echo $this->getPageGridUrl() ?>');
    }
    
    
    
    
    function setProductRedirectionUrlFromGrid(grid, event) {
        var trElement = Event.findElement(event, 'tr');
        var isInput = Event.element(event).tagName == 'INPUT';
        if (trElement) {
            var urlKey = Element.select(trElement, '.pr_url_key');
            if(urlKey[0]) {
                setProductRedirectionUrl(urlKey[0].innerHTML.replace(/^\s+|\s+$/g, ''));
            }
        }
    }
</script>
